# Generated by Django 5.0.6 on 2024-06-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='mission_type',
            new_name='specialty',
        ),
    ]
